<?php

namespace Database\Seeders;

use App\Models\Kegiatan;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KegiatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kegiatan = [
        
        ['kode_kegiatan' => '04.001', 'kegiatan' => 'SUMBANGAN SPP'],
        ['kode_kegiatan' => '04.002', 'kegiatan' => 'SUMBANGAN KOMITE'],
        ['kode_kegiatan' => '04.003', 'kegiatan' => 'SUMBANGAN DANA KEGIATAN SEKOLAH'],
        ['kode_kegiatan' => '04.004', 'kegiatan' => 'SUMBANGAN PEMBANGUNAN'],
        ['kode_kegiatan' => '04.005', 'kegiatan' => 'SUMBANGAN KEGIATAN PEMANTAPAN'],
        ['kode_kegiatan' => '04.006', 'kegiatan' => 'SUMBANGAN KEGIATAN PERPISAHAN'],
        ['kode_kegiatan' => '04.007', 'kegiatan' => 'SUMBANGAN KEGIATAN US'],
        ['kode_kegiatan' => '04.008', 'kegiatan' => 'SUMBANGAN DANA BOS/ BOP'],
        ['kode_kegiatan' => '04.009', 'kegiatan' => 'SUMBANGAN KEGIATAN ANBK'],
        ['kode_kegiatan' => '04.010', 'kegiatan' => 'SUMBANGAN KEGIATAN UKK'],
        ['kode_kegiatan' => '04.011', 'kegiatan' => 'SUMBANGAN KEGIATAN PRAKERIN'],
        ['kode_kegiatan' => '04.012', 'kegiatan' => 'SUMBANGAN KEGIATAN BOARDING'],
        ['kode_kegiatan' => '04.013', 'kegiatan' => 'PENERIMAAN BUKU'],
        ['kode_kegiatan' => '04.014', 'kegiatan' => 'PENERIMAAN SERAGAM'],
        ['kode_kegiatan' => '04.015', 'kegiatan' => 'PENERIMAAN PPDB'],
        ['kode_kegiatan' => '04.016', 'kegiatan' => 'PENERIMAAN KATERING'],
        ['kode_kegiatan' => '04.017', 'kegiatan' => 'PENERIMAAN TRANSPORTASI'],
        ['kode_kegiatan' => '04.018', 'kegiatan' => 'SUMBANGAN PENITIPAN ANAK'],
        ['kode_kegiatan' => '04.019', 'kegiatan' => 'SUMBANGAN HIBAH, WAKAF PENDIDIKAN'],
        ['kode_kegiatan' => '04.020', 'kegiatan' => 'PENERIMAAN LAINNYA'],
        ['kode_kegiatan' => '05.01.001', 'kegiatan' => 'BELANJA GAJI PEGAWAI'],
        ['kode_kegiatan' => '05.01.002', 'kegiatan' => 'BELANJA JAMINAN SOSIAL & KESEJAHTERAAN'],
        ['kode_kegiatan' => '05.01.003', 'kegiatan' => 'LEMBUR HARI LIBUR'],
        ['kode_kegiatan' => '05.01.004', 'kegiatan' => 'CADANGAN IMBALAN PASCA KERJA'],
        ['kode_kegiatan' => '05.02.001', 'kegiatan' => 'SUPERVISI PEMBELAJARAN'],
        ['kode_kegiatan' => '05.02.002', 'kegiatan' => 'PELAKSANAAN RAPAT KERJA KEPALA SEKOLAH (K3S,SUPERVISI SILANG DLL)'],
        ['kode_kegiatan' => '05.02.003', 'kegiatan' => 'PEMBUATAN PROGRAM KERJA KEPALA SEKOLAH (PEMBUATAN DOKUMENTASI 1 DENGAN WAKAKUR)'],
        ['kode_kegiatan' => '05.02.004', 'kegiatan' => 'GURU TAMU'],
        ['kode_kegiatan' => '05.02.005', 'kegiatan' => 'KEWIRAUSAHAAN'],
        ['kode_kegiatan' => '05.03.001', 'kegiatan' => 'AKSELERASI TAHFIDZ'],
        ['kode_kegiatan' => '05.03.002', 'kegiatan' => 'PRA WISUDA TAHFIDZ'],
        ['kode_kegiatan' => '05.03.003', 'kegiatan' => 'WISUDA TAHFIDZ'],
        ['kode_kegiatan' => '05.03.004', 'kegiatan' => 'HALAQAH TAHFIDZ'],
        ['kode_kegiatan' => '05.03.005', 'kegiatan' => 'MANASIK HAJI'],
        ['kode_kegiatan' => '05.03.006', 'kegiatan' => 'SPIRITUAL CAMP'],
        ['kode_kegiatan' => '05.03.007', 'kegiatan' => 'OLIMPIADE OLAHRAGA SISWA NASIONAL (O2SN)'],
        ['kode_kegiatan' => '05.03.008', 'kegiatan' => 'FESTIVAL LOMBA SENI SISWA NASIONAL (FLS2N)'],
        ['kode_kegiatan' => '05.03.009', 'kegiatan' => 'SISWA BERPRESTASI'],
        ['kode_kegiatan' => '05.03.010', 'kegiatan' => 'LOMBA CC VARIA PENDIDIKAN'],
        ['kode_kegiatan' => '05.03.011', 'kegiatan' => 'LOMBA YEL-YEL VARIA PENDIDIKAN'],
        ['kode_kegiatan' => '05.03.012', 'kegiatan' => 'OLIMPIADE SAINS TINGKAT KOTA'],
        ['kode_kegiatan' => '05.03.013', 'kegiatan' => 'LOMBA MTQ'],
        ['kode_kegiatan' => '05.03.014', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PRAMUKA'],
        ['kode_kegiatan' => '05.03.015', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BOLA VOLLEY'],
        ['kode_kegiatan' => '05.03.016', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER TENNIS MEJA'],
        ['kode_kegiatan' => '05.03.017', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER FUTSAL'],
        ['kode_kegiatan' => '05.03.018', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER ARABIAN CLUB'],
        ['kode_kegiatan' => '05.03.019', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BOLA BASKET'],
        ['kode_kegiatan' => '05.03.020', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BULU TANGKIS'],
        ['kode_kegiatan' => '05.03.021', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MEMASAK'],
        ['kode_kegiatan' => '05.03.022', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MENGGAMBAR'],
        ['kode_kegiatan' => '05.03.023', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KEPUTRIAN'],
        ['kode_kegiatan' => '05.03.024', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PENCAK SILAT'],
        ['kode_kegiatan' => '05.03.025', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BAHASA JEPANG'],
        ['kode_kegiatan' => '05.03.026', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER SOLO VOCAL'],
        ['kode_kegiatan' => '05.03.027', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KEMPO'],
        ['kode_kegiatan' => '05.03.028', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER TAHFIZH QURAN'],
        ['kode_kegiatan' => '05.03.029', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MENARI'],
        ['kode_kegiatan' => '05.03.030', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER JURNALISTIK'],
        ['kode_kegiatan' => '05.03.031', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PMR'],
        ['kode_kegiatan' => '05.03.032', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER ENGLISH CLUB'],
        ['kode_kegiatan' => '05.03.033', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KOMPUTER'],
        ['kode_kegiatan' => '05.03.034', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER DRUMBAND'],
        ['kode_kegiatan' => '05.03.035', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PASKIBRA'],
        ['kode_kegiatan' => '05.03.036', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER IQRA'],
        ['kode_kegiatan' => '05.03.037', 'kegiatan' => 'KEMAH BUDAYA'],
        ['kode_kegiatan' => '05.03.038', 'kegiatan' => 'PESANTREN KILAT RAMADHAN'],
        ['kode_kegiatan' => '05.03.039', 'kegiatan' => 'PELAKSANAAN KEGIATAN RIHLAH/ TADABUR ALAM'],
        ['kode_kegiatan' => '05.03.040', 'kegiatan' => 'PELAKSANAAN MASA PENGENALAN LINGKUNGAN SEKOLAH'],
        ['kode_kegiatan' => '05.03.041', 'kegiatan' => 'PROJECT JURUSAN'],
        ['kode_kegiatan' => '05.03.042', 'kegiatan' => 'PENERIMAAN PESERTA DIDIK BARU'],
        ['kode_kegiatan' => '05.03.043', 'kegiatan' => 'SEMINAR MOTIVASI SISWA'],
        ['kode_kegiatan' => '05.03.044', 'kegiatan' => 'KEGIATAN TASYAKURAN/ HAFLAH AKHIRUSSANAH'],
        ['kode_kegiatan' => '05.03.045', 'kegiatan' => 'MAKAN DAN MINUM SEHAT'],
        ['kode_kegiatan' => '05.03.046', 'kegiatan' => 'PERINGATAN HUT RI & LOMBA SISWA'],
        ['kode_kegiatan' => '05.03.047', 'kegiatan' => 'HUT KEPRI'],
        ['kode_kegiatan' => '05.03.048', 'kegiatan' => 'HUT PGRI'],
        ['kode_kegiatan' => '05.03.049', 'kegiatan' => 'HARI PAHLAWAN'],
        ['kode_kegiatan' => '05.03.050', 'kegiatan' => 'HARI SUMPAH PEMUDA'],
        ['kode_kegiatan' => '05.03.051', 'kegiatan' => 'IDUL ADHA'],
        ['kode_kegiatan' => '05.03.052', 'kegiatan' => 'RAMADHAN'],
        ['kode_kegiatan' => '05.03.053', 'kegiatan' => 'PERINGATAN 1 MUHARRAM'],
        ['kode_kegiatan' => '05.03.054', 'kegiatan' => 'PERINGATAN MAULID NABI'],
        ['kode_kegiatan' => '05.03.055', 'kegiatan' => 'PERINGATAN ISRA MI\'RAJ'],
        ['kode_kegiatan' => '05.03.056', 'kegiatan' => 'PERINGATAN NUZULUL QUR\'AN'],
        ['kode_kegiatan' => '05.03.057', 'kegiatan' => 'OSIS'],
        ['kode_kegiatan' => '05.03.058', 'kegiatan' => 'TEST TOEIC'],
        ['kode_kegiatan' => '05.03.059', 'kegiatan' => 'TEST TOEFL'],
        ['kode_kegiatan' => '05.03.060', 'kegiatan' => 'TEST IQ'],
        ['kode_kegiatan' => '05.03.061', 'kegiatan' => 'PENYULUHAN SISWA'],
        ['kode_kegiatan' => '05.03.062', 'kegiatan' => 'LOMBA TINGKAT KECAMATAN'],
        ['kode_kegiatan' => '05.03.063', 'kegiatan' => 'LOMBA TINGKAT KOTA'],
        ['kode_kegiatan' => '05.03.064', 'kegiatan' => 'LOMBA TINGKAT PROVINSI'],
        ['kode_kegiatan' => '05.03.065', 'kegiatan' => 'LOMBA TINGKAT NASIONAL'],
        ['kode_kegiatan' => '05.03.066', 'kegiatan' => 'OLIMPIADE SAINS NASIONAL'],
        ['kode_kegiatan' => '05.03.067', 'kegiatan' => 'KEGIATAN TASMI\''],
        ['kode_kegiatan' => '05.03.068', 'kegiatan' => 'TURNAMEN FUTSAL'],
        ['kode_kegiatan' => '05.03.069', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER HADROH'],
        ['kode_kegiatan' => '05.03.070', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER CATUR'],
        ['kode_kegiatan' => '05.03.071', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER ANIMASI'],
        ['kode_kegiatan' => '05.03.072', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER TAKRAW'],
        ['kode_kegiatan' => '05.03.073', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER ATLETIK'],
        ['kode_kegiatan' => '05.03.074', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER DESIGN GRAFIS'],
        ['kode_kegiatan' => '05.03.075', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER SENI KRIYA'],
        ['kode_kegiatan' => '05.03.076', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER STORY TELLING'],
        ['kode_kegiatan' => '05.03.077', 'kegiatan' => 'HIDROPONIK'],
        ['kode_kegiatan' => '05.03.078', 'kegiatan' => 'KEMAH PRAMUKA'],
        ['kode_kegiatan' => '05.03.079', 'kegiatan' => 'GEBYAR DARUSSALAM'],
        ['kode_kegiatan' => '05.03.080', 'kegiatan' => 'LOMBA KOMPETENSI SISWA'],
        ['kode_kegiatan' => '05.03.081', 'kegiatan' => 'KEGIATAN LITERASI DAN NUMERASI SISWA'],
        ['kode_kegiatan' => '05.03.082', 'kegiatan' => 'KEGIATAN PENANGANAN DAN PENCEGAHAN KEKERASAN'],
        ['kode_kegiatan' => '05.03.083', 'kegiatan' => 'HARI AMAL BAKTI KEMENAG'],
        ['kode_kegiatan' => '05.03.084', 'kegiatan' => 'PROGRAM MAGANG JEPANG'],
        ['kode_kegiatan' => '05.03.085', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER ROBOTIK'],
        ['kode_kegiatan' => '05.03.086', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER PANTOMIM'],
        ['kode_kegiatan' => '05.03.087', 'kegiatan' => 'KEGIATAN PMR/ PMI'],
        ['kode_kegiatan' => '05.03.088', 'kegiatan' => 'KOMPETISI (OLIMPIADE) SAIN MADRASAH'],
        ['kode_kegiatan' => '05.03.089', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER SAINS'],
        ['kode_kegiatan' => '05.03.090', 'kegiatan' => 'BIMBINGAN TAHFIDZ, TARTIL DAN TAHSIN SISWA'],
        ['kode_kegiatan' => '05.04.001', 'kegiatan' => 'PELATIHAN METODE PEMBELAJARAN'],
        ['kode_kegiatan' => '05.04.002', 'kegiatan' => 'UP GRADING & TEAM BUILDING'],
        ['kode_kegiatan' => '05.04.003', 'kegiatan' => 'PELATIHAN KEPSEK & KEPALA DEPARTEMEN'],
        ['kode_kegiatan' => '05.04.004', 'kegiatan' => 'PELATIHAN GURU ISLAM TERPADU'],
        ['kode_kegiatan' => '05.04.005', 'kegiatan' => 'PELATIHAN GURU BIDANG STUDI'],
        ['kode_kegiatan' => '05.04.006', 'kegiatan' => 'STUDI BANDING'],
        ['kode_kegiatan' => '05.04.007', 'kegiatan' => 'BIMBINGAN TAHFIDZ, TARTIL DAN TAHSIN GURU'],
        ['kode_kegiatan' => '05.04.008', 'kegiatan' => 'KEGIATAN KKG/MGMP ATAU KKKS/MKKS'],
        ['kode_kegiatan' => '05.04.009', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI EVALUASI PEMBELAJARAN'],
        ['kode_kegiatan' => '05.04.010', 'kegiatan' => 'PELATIHAN PEMBUATAN CLOUDING DATA'],
        ['kode_kegiatan' => '05.04.011', 'kegiatan' => 'PELATIHAN GURU DAN KEPALA SEKOLAH TERKAIT PERUNDUNGAN'],
        ['kode_kegiatan' => '05.04.012', 'kegiatan' => 'PROGRAM UMROH GURU & KARYAWAN'],
        ['kode_kegiatan' => '05.04.013', 'kegiatan' => 'PENYELENGGARAAN KURSUS ICT'],
        ['kode_kegiatan' => '05.04.014', 'kegiatan' => 'PENYELENGGARAAN GURU BERPRESTASI'],
        ['kode_kegiatan' => '05.04.015', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI PENGELOLAAN KEUANGAN SEKOLAH'],
        ['kode_kegiatan' => '05.04.016', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI BIDANG ADMINISTRASI SEKOLAH'],
        ['kode_kegiatan' => '05.04.017', 'kegiatan' => 'PEMBINAAN TENAGA KETATAUSAHAAN'],
        ['kode_kegiatan' => '05.04.018', 'kegiatan' => 'PEMBINAAN TENAGA PERPUSTAKAAN/PENINGKATAN KOMPETENSI TENAGA PERPUSTAKAAN'],
        ['kode_kegiatan' => '05.04.019', 'kegiatan' => 'PELATIHAN KEAMANAN & KESELAMATAN KERJA'],
        ['kode_kegiatan' => '05.04.020', 'kegiatan' => 'PELATIHAN EXCEL'],
        ['kode_kegiatan' => '05.04.021', 'kegiatan' => 'PROGRAM GURU PENGGERAK'],
        ['kode_kegiatan' => '05.04.022', 'kegiatan' => 'PEMBINAAN KEPRIBADIAN GURU'],
        ['kode_kegiatan' => '05.04.023', 'kegiatan' => 'PEMBINAAN TENAGA KEAMANAN & TENAGA KEBERSIHAN'],
        ['kode_kegiatan' => '05.04.024', 'kegiatan' => 'DAUROH TAHFIDZ'],
        ['kode_kegiatan' => '05.04.025', 'kegiatan' => 'KEGIATAN LITERASI GURU'],
        ['kode_kegiatan' => '05.04.026', 'kegiatan' => 'KEGIATAN PENGAJIAN BULANAN'],
        ['kode_kegiatan' => '05.05.001', 'kegiatan' => 'PEMBANGUNAN RUANG KELAS BARU (RKB)'],
        ['kode_kegiatan' => '05.05.002', 'kegiatan' => 'PEMBANGUNAN SARANA IBADAH'],
        ['kode_kegiatan' => '05.05.003', 'kegiatan' => 'PENAMBAHAN RUANG IBADAH SISWA'],
        ['kode_kegiatan' => '05.05.004', 'kegiatan' => 'PENAMBAHAN RUANG LABORATORIUM KOMPUTER'],
        ['kode_kegiatan' => '05.05.005', 'kegiatan' => 'PENAMBAHAN RUANG PERPUSTAKAAN'],
        ['kode_kegiatan' => '05.05.006', 'kegiatan' => 'PENAMBAHAN RUANG KANTOR'],
        ['kode_kegiatan' => '05.05.007', 'kegiatan' => 'PEMBUATAN TOILET'],
        ['kode_kegiatan' => '05.05.008', 'kegiatan' => 'BELANJA MODAL ALAT BENGKEL'],
        ['kode_kegiatan' => '05.05.009', 'kegiatan' => 'BELANJA MODAL ALAT KANTOR & RUMAH TANGGA'],
        ['kode_kegiatan' => '05.05.010', 'kegiatan' => 'BELANJA MODAL ALAT STUDIO DAN KOMUNIKASI'],
        ['kode_kegiatan' => '05.05.011', 'kegiatan' => 'BELANJA MODAL ALAT LABORATORIUM'],
        ['kode_kegiatan' => '05.05.012', 'kegiatan' => 'BELANJA MODAL KOMPUTER'],
        ['kode_kegiatan' => '05.05.013', 'kegiatan' => 'PERALATAN OLAHRAGA SISWA'],
        ['kode_kegiatan' => '05.05.014', 'kegiatan' => 'BELANJA MODAL BUKU'],
        ['kode_kegiatan' => '05.05.015', 'kegiatan' => 'BELANJA MODAL BARANG KESENIAN'],
        ['kode_kegiatan' => '05.05.016', 'kegiatan' => 'BELANJA MODAL TANAH'],
        ['kode_kegiatan' => '05.05.017', 'kegiatan' => 'BELANJA MODAL BANGUNAN'],
        ['kode_kegiatan' => '05.05.018', 'kegiatan' => 'PENGADAAN PAPAN PENGUMUMAN'],
        ['kode_kegiatan' => '05.05.019', 'kegiatan' => 'PENGADAAN MEUBELAIR'],
        ['kode_kegiatan' => '05.05.020', 'kegiatan' => 'PENGADAAN PROYEKTOR'],
        ['kode_kegiatan' => '05.05.021', 'kegiatan' => 'PENAMBAHAN RUANG KEGIATAN'],
        ['kode_kegiatan' => '05.05.022', 'kegiatan' => 'PENGADAAN PRINTER'],
        ['kode_kegiatan' => '05.05.023', 'kegiatan' => 'PENGADAAN PAPAN TULIS'],
        ['kode_kegiatan' => '05.06.001', 'kegiatan' => 'AKREDITASI SEKOLAH'],
        ['kode_kegiatan' => '05.06.002', 'kegiatan' => 'PERJALANAN DINAS'],
        ['kode_kegiatan' => '05.06.003', 'kegiatan' => 'PENGELOLAAN INVENTARIS BARANG'],
        ['kode_kegiatan' => '05.06.004', 'kegiatan' => 'PENGEMBANGAN SISTEM INFORMASI MANAJEMEN (WEBSITE, E-LEARNING, SOSIAL MEDIA)'],
        ['kode_kegiatan' => '05.06.005', 'kegiatan' => 'PENYUSUNAN LEAFLET, POSTER'],
        ['kode_kegiatan' => '05.06.006', 'kegiatan' => 'SOSIALISASI KEBIJAKAN-KEBIJAKAN'],
        ['kode_kegiatan' => '05.06.007', 'kegiatan' => 'PENYUSUNAN RKAS DAN LAPORAN DANA BOS/ BOP'],
        ['kode_kegiatan' => '05.06.008', 'kegiatan' => 'PENYUSUNAN RAPBS'],
        ['kode_kegiatan' => '05.06.009', 'kegiatan' => 'PENYUSUNAN JADWAL PELAJARAN'],
        ['kode_kegiatan' => '05.06.010', 'kegiatan' => 'STANDAR ISO'],
        ['kode_kegiatan' => '05.06.011', 'kegiatan' => 'PROGRAM EKSTERNAL AUDIT KEUANGAN'],
        ['kode_kegiatan' => '05.06.012', 'kegiatan' => 'KEGIATAN PUBLIKASI & MEDIA SOSIAL'],
        ['kode_kegiatan' => '05.06.013', 'kegiatan' => 'PEMBUATAN KALENDER'],
        ['kode_kegiatan' => '05.06.014', 'kegiatan' => 'RAPAT KERJA TAHUNAN PENGURUS YAYASAN'],
        ['kode_kegiatan' => '05.06.015', 'kegiatan' => 'PELAPORAN & PERENCANAAN KERJA KEPALA SEKOLAH - KEPALA DEPARTEMEN'],
        ['kode_kegiatan' => '05.06.016', 'kegiatan' => 'PERINGATAN HUT RI & PENGHARGAAN PENGABDIAN, GURU BERPRESTASI'],
        ['kode_kegiatan' => '05.06.017', 'kegiatan' => 'PENYULUHAN KESEHATAN BAGI GURU & KARYAWAN'],
        ['kode_kegiatan' => '05.06.018', 'kegiatan' => 'KEGIATAN POS'],
        ['kode_kegiatan' => '05.06.019', 'kegiatan' => 'PELAKSANAAN MOU KERJASAMA'],
        ['kode_kegiatan' => '05.06.020', 'kegiatan' => 'PENGELOLAAN TABUNGAN SEKOLAH'],
        ['kode_kegiatan' => '05.06.021', 'kegiatan' => 'PENYUSUNAN SOP'],
        ['kode_kegiatan' => '05.06.022', 'kegiatan' => 'DANA ORGAN YAYASAN'],
        ['kode_kegiatan' => '05.06.023', 'kegiatan' => 'PENGELOLAAN DATABASE PENDIDIKAN'],
        ['kode_kegiatan' => '05.06.024', 'kegiatan' => 'KEGIATAN HOME VISIT'],
        ['kode_kegiatan' => '05.06.025', 'kegiatan' => 'KEGIATAN PARENTING'],
        ['kode_kegiatan' => '05.06.026', 'kegiatan' => 'HALAL BI HALAL'],
        ['kode_kegiatan' => '05.07.001', 'kegiatan' => 'KONSUMSI MAKAN SIANG GURU & KARYAWAN'],
        ['kode_kegiatan' => '05.07.002', 'kegiatan' => 'KONSUMSI KANTOR'],
        ['kode_kegiatan' => '05.07.003', 'kegiatan' => 'KONSUMSI SISWA'],
        ['kode_kegiatan' => '05.07.004', 'kegiatan' => 'KONSUMSI TAMU'],
        ['kode_kegiatan' => '05.07.005', 'kegiatan' => 'KONSUMSI RAPAT'],
        ['kode_kegiatan' => '05.07.006', 'kegiatan' => 'BELANJA BAHAN BAKAR MINYAK'],
        ['kode_kegiatan' => '05.07.007', 'kegiatan' => 'PEMELIHARAAN GEDUNG'],
        ['kode_kegiatan' => '05.07.008', 'kegiatan' => 'PERBAIKAN KERUSAKAN RINGAN'],
        ['kode_kegiatan' => '05.07.009', 'kegiatan' => 'PEMELIHARAAN TAMAN SEKOLAH'],
        ['kode_kegiatan' => '05.07.010', 'kegiatan' => 'PEMELIHARAAN INVENTARIS & PERALATAN'],
        ['kode_kegiatan' => '05.07.011', 'kegiatan' => 'PENGADAAN PERLENGKAPAN INDIVIDU SISWA'],
        ['kode_kegiatan' => '05.07.012', 'kegiatan' => 'PENGADAAN PERALATAN KEBERSIHAN'],
        ['kode_kegiatan' => '05.07.013', 'kegiatan' => 'PENGADAAN PERALATAN RUANG UKS'],
        ['kode_kegiatan' => '05.07.014', 'kegiatan' => 'PROTOKOL KESEHATAN COVID-19'],
        ['kode_kegiatan' => '05.07.015', 'kegiatan' => 'BELANJA ALAT TULIS KANTOR'],
        ['kode_kegiatan' => '05.07.016', 'kegiatan' => 'BELANJA OBAT-OBATAN UKS'],
        ['kode_kegiatan' => '05.07.017', 'kegiatan' => 'BELANJA BAHAN KEBERSIHAN HABIS PAKAI'],
        ['kode_kegiatan' => '05.07.018', 'kegiatan' => 'BELANJA KERUMAHTANGGAAN LAINNYA'],
        ['kode_kegiatan' => '05.07.019', 'kegiatan' => 'PEMBAYARAN TAGIHAN LISTRIK'],
        ['kode_kegiatan' => '05.07.020', 'kegiatan' => 'PEMBAYARAN TAGIHAN INTERNET'],
        ['kode_kegiatan' => '05.07.021', 'kegiatan' => 'PEMBAYARAN TAGIHAN AIR'],
        ['kode_kegiatan' => '05.07.022', 'kegiatan' => 'PEMBAYARAN TAGIHAN TELEPON'],
        ['kode_kegiatan' => '05.07.023', 'kegiatan' => 'PEMBAYARAN JASA KURIR'],
        ['kode_kegiatan' => '05.07.024', 'kegiatan' => 'PEMBAYARAN PULSA'],
        ['kode_kegiatan' => '05.07.025', 'kegiatan' => 'PEMBAYARAN PAKET DATA'],
        ['kode_kegiatan' => '05.07.026', 'kegiatan' => 'SEWA GOOGLE DRIVE'],
        ['kode_kegiatan' => '05.07.027', 'kegiatan' => 'SEWA HOSTING'],
        ['kode_kegiatan' => '05.07.028', 'kegiatan' => 'SEWA WA BLASTER'],
        ['kode_kegiatan' => '05.07.029', 'kegiatan' => 'LANGGANAN KORAN'],
        ['kode_kegiatan' => '05.07.030', 'kegiatan' => 'SEWA AIR FRESHENER'],
        ['kode_kegiatan' => '05.07.031', 'kegiatan' => 'SEDOT WC'],
        ['kode_kegiatan' => '05.07.032', 'kegiatan' => 'PENYEDIAAN AIR BERSIH'],
        ['kode_kegiatan' => '05.07.033', 'kegiatan' => 'PENAMBAHAN DAYA LISTRIK'],
        ['kode_kegiatan' => '05.07.034', 'kegiatan' => 'INSTALASI LISTRIK BARU'],
        ['kode_kegiatan' => '05.07.035', 'kegiatan' => 'INSTALASI JARINGAN INTERNET BARU'],
        ['kode_kegiatan' => '05.07.036', 'kegiatan' => 'INSTALASI AIR BARU'],
        ['kode_kegiatan' => '05.07.037', 'kegiatan' => 'RETRIBUSI PEMBUANGAN SAMPAH'],
        ['kode_kegiatan' => '05.07.038', 'kegiatan' => 'SEWA GEDUNG/ RUMAH/ TANAH'],
        ['kode_kegiatan' => '05.07.039', 'kegiatan' => 'BELANJA DANA SOSIAL (TAAWUN)/ KEMASYARAKATAN'],
        ['kode_kegiatan' => '05.07.040', 'kegiatan' => 'PENGADAAN BUKU SISWA'],
        ['kode_kegiatan' => '05.07.041', 'kegiatan' => 'PENGADAAN SERAGAM SISWA'],
        ['kode_kegiatan' => '05.07.042', 'kegiatan' => 'PENGADAAN SERAGAM GURU'],
        ['kode_kegiatan' => '05.07.043', 'kegiatan' => 'BESUK SISWA SAKIT'],
        ['kode_kegiatan' => '05.07.044', 'kegiatan' => 'KEGIATAN VAKSINASI'],
        ['kode_kegiatan' => '05.07.045', 'kegiatan' => 'ADMINISTRASI BANK'],
        ['kode_kegiatan' => '05.07.046', 'kegiatan' => 'ASURANSI'],
        ['kode_kegiatan' => '05.07.047', 'kegiatan' => 'PAJAK'],
        ['kode_kegiatan' => '05.07.048', 'kegiatan' => 'TRANSPORTASI SISWA'],
        ['kode_kegiatan' => '05.07.049', 'kegiatan' => 'KATERING SISWA'],
        ['kode_kegiatan' => '05.07.050', 'kegiatan' => 'IURAN DAPODIK'],
        ['kode_kegiatan' => '05.07.051', 'kegiatan' => 'IURAN KKG'],
        ['kode_kegiatan' => '05.07.052', 'kegiatan' => 'IURAN K3S'],
        ['kode_kegiatan' => '05.07.053', 'kegiatan' => 'IURAN HUT RI'],
        ['kode_kegiatan' => '05.07.054', 'kegiatan' => 'IURAN BMG KEMENAG'],
        ['kode_kegiatan' => '05.07.055', 'kegiatan' => 'IURAN IGRA'],
        ['kode_kegiatan' => '05.07.056', 'kegiatan' => 'BELANJA AIR MINUM'],
        ['kode_kegiatan' => '05.07.057', 'kegiatan' => 'LAUNDRY'],
        ['kode_kegiatan' => '05.07.058', 'kegiatan' => 'SEWA TEMPAT OLAHRAGA'],
        ['kode_kegiatan' => '05.07.059', 'kegiatan' => 'SEWA PERALATAN KEGIATAN'],
        ['kode_kegiatan' => '05.07.060', 'kegiatan' => 'FOGGING'],
        ['kode_kegiatan' => '05.08.001', 'kegiatan' => 'ULANGAN HARIAN'],
        ['kode_kegiatan' => '05.08.002', 'kegiatan' => 'PENILAIAN/ SUMATIF TENGAH SEMESTER GANJIL'],
        ['kode_kegiatan' => '05.08.003', 'kegiatan' => 'PENILAIAN AKHIR SEMESTER GANJIL'],
        ['kode_kegiatan' => '05.08.004', 'kegiatan' => 'PENILAIAN/ SUMATIF TENGAH SEMESTER GENAP'],
        ['kode_kegiatan' => '05.08.005', 'kegiatan' => 'PENILAIAN AKHIR TAHUN'],
        ['kode_kegiatan' => '05.08.006', 'kegiatan' => 'CLASS MEETING PENILAIAN AKHIR SEMESTER GANJIL'],
        ['kode_kegiatan' => '05.08.007', 'kegiatan' => 'CLASS MEETING PENILAIAN AKHIR TAHUN'],
        ['kode_kegiatan' => '05.08.008', 'kegiatan' => 'TRY OUT'],
        ['kode_kegiatan' => '05.08.009', 'kegiatan' => 'UJIAN PRAKTIK'],
        ['kode_kegiatan' => '05.08.010', 'kegiatan' => 'AKM/ ANBK'],
        ['kode_kegiatan' => '05.08.011', 'kegiatan' => 'UJIAN SEKOLAH'],
        ['kode_kegiatan' => '05.08.012', 'kegiatan' => 'PELAKSANAAN UJI KOMPETENSI SISWA'],
        ['kode_kegiatan' => '05.08.013', 'kegiatan' => 'PELAKSANAAN PRAKTIK INDUSTRI'],
        ['kode_kegiatan' => '05.08.014', 'kegiatan' => 'PELAKSANAAN BURSA KERJA KHUSUS'],
        ['kode_kegiatan' => '05.08.015', 'kegiatan' => 'LEARNING FACTORY'],
        ['kode_kegiatan' => '05.08.016', 'kegiatan' => 'P5 SEMESTER GANJIL'],
        ['kode_kegiatan' => '05.08.017', 'kegiatan' => 'P5 SEMESTER GENAP'],
        ['kode_kegiatan' => '05.08.018', 'kegiatan' => 'KEGIATAN PEMANTAPAN'],
        ['kode_kegiatan' => '05.08.019', 'kegiatan' => 'KEGIATAN ASSESMEN MINAT BAKAT'],
        ['kode_kegiatan' => '05.08.020', 'kegiatan' => 'PENINGKATAN MUTU PRAKTIK IBADAH'],
        

















        // ['kode_kegiatan' => '04.001', 'kegiatan' => 'SUMBANGAN SPP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.002', 'kegiatan' => 'SUMBANGAN KOMITE', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.003', 'kegiatan' => 'SUMBANGAN DANA KEGIATAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.004', 'kegiatan' => 'SUMBANGAN PEMBANGUNAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.005', 'kegiatan' => 'SUMBANGAN KEGIATAN PEMANTAPAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.006', 'kegiatan' => 'SUMBANGAN KEGIATAN PERPISAHAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.007', 'kegiatan' => 'SUMBANGAN KEGIATAN US', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.008', 'kegiatan' => 'SUMBANGAN DANA BOS/ BOP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.009', 'kegiatan' => 'SUMBANGAN KEGIATAN ANBK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.010', 'kegiatan' => 'SUMBANGAN KEGIATAN UKK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.011', 'kegiatan' => 'SUMBANGAN KEGIATAN PRAKERIN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.012', 'kegiatan' => 'SUMBANGAN KEGIATAN BOARDING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.013', 'kegiatan' => 'PENERIMAAN BUKU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.014', 'kegiatan' => 'PENERIMAAN SERAGAM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.015', 'kegiatan' => 'PENERIMAAN PPDB', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.016', 'kegiatan' => 'PENERIMAAN KATERING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.017', 'kegiatan' => 'PENERIMAAN TRANSPORTASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.018', 'kegiatan' => 'SUMBANGAN PENITIPAN ANAK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.019', 'kegiatan' => 'SUMBANGAN HIBAH, WAKAF PENDIDIKAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '04.020', 'kegiatan' => 'PENERIMAAN LAINNYA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.01.001', 'kegiatan' => 'BELANJA GAJI PEGAWAI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.01.002', 'kegiatan' => 'BELANJA JAMINAN SOSIAL & KESEJAHTERAAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.01.003', 'kegiatan' => 'LEMBUR HARI LIBUR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.01.004', 'kegiatan' => 'CADANGAN IMBALAN PASCA KERJA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.02.001', 'kegiatan' => 'SUPERVISI PEMBELAJARAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.02.002', 'kegiatan' => 'PELAKSANAAN RAPAT KERJA KEPALA SEKOLAH (K3S,SUPERVISI SILANG DLL)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.02.003', 'kegiatan' => 'PEMBUATAN PROGRAM KERJA KEPALA SEKOLAH (PEMBUATAN DOKUMENTASI 1 DENGAN WAKAKUR)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.02.004', 'kegiatan' => 'GURU TAMU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.02.005', 'kegiatan' => 'KEWIRAUSAHAAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.001', 'kegiatan' => 'AKSELERASI TAHFIDZ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.002', 'kegiatan' => 'PRA WISUDA TAHFIDZ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.003', 'kegiatan' => 'WISUDA TAHFIDZ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.004', 'kegiatan' => 'HALAQAH TAHFIDZ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.005', 'kegiatan' => 'MANASIK HAJI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.006', 'kegiatan' => 'SPIRITUAL CAMP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.007', 'kegiatan' => 'OLIMPIADE OLAHRAGA SISWA NASIONAL (O2SN)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.008', 'kegiatan' => 'FESTIVAL LOMBA SENI SISWA NASIONAL (FLS2N)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.009', 'kegiatan' => 'SISWA BERPRESTASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.010', 'kegiatan' => 'LOMBA CC VARIA PENDIDIKAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.011', 'kegiatan' => 'LOMBA YEL-YEL VARIA PENDIDIKAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.012', 'kegiatan' => 'OLIMPIADE SAINS TINGKAT KOTA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.013', 'kegiatan' => 'LOMBA MTQ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.014', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PRAMUKA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.015', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BOLA VOLLEY', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.016', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER TENNIS MEJA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.017', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER FUTSAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.018', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER ARABIAN CLUB', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.019', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BOLA BASKET', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.020', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BULU TANGKIS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.021', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MEMASAK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.022', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MENGGAMBAR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.023', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KEPUTRIAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.024', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PENCAK SILAT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.025', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER BAHASA JEPANG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.026', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER SOLO VOCAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.027', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KEMPO', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.028', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER TAHFIZH QURAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.029', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER MENARI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.030', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER JURNALISTIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.031', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PMR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.032', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER ENGLISH CLUB', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.033', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER KOMPUTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.034', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER DRUMBAND', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.035', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER PASKIBRA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.036', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKURIKULER IQRA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.037', 'kegiatan' => 'KEMAH BUDAYA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.038', 'kegiatan' => 'PESANTREN KILAT RAMADHAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.039', 'kegiatan' => 'PELAKSANAAN KEGIATAN RIHLAH/ TADABUR ALAM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.040', 'kegiatan' => 'PELAKSANAAN MASA PENGENALAN LINGKUNGAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.041', 'kegiatan' => 'PROJECT JURUSAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.042', 'kegiatan' => 'PENERIMAAN PESERTA DIDIK BARU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.043', 'kegiatan' => 'SEMINAR MOTIVASI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.044', 'kegiatan' => 'KEGIATAN TASYAKURAN/ HAFLAH AKHIRUSSANAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.045', 'kegiatan' => 'MAKAN DAN MINUM SEHAT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.046', 'kegiatan' => 'PERINGATAN HUT RI & LOMBA SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.047', 'kegiatan' => 'HUT KEPRI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.048', 'kegiatan' => 'HUT PGRI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.049', 'kegiatan' => 'HARI PAHLAWAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.050', 'kegiatan' => 'HARI SUMPAH PEMUDA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.051', 'kegiatan' => 'IDUL ADHA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.052', 'kegiatan' => 'RAMADHAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.053', 'kegiatan' => 'PERINGATAN 1 MUHARRAM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.054', 'kegiatan' => 'PERINGATAN MAULID NABI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.055', 'kegiatan' => 'PERINGATAN ISRA MI\'RAJ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.056', 'kegiatan' => 'PERINGATAN NUZULUL QUR\'AN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.057', 'kegiatan' => 'OSIS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.058', 'kegiatan' => 'TEST TOEIC', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.059', 'kegiatan' => 'TEST TOEFL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.060', 'kegiatan' => 'TEST IQ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.061', 'kegiatan' => 'PENYULUHAN SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.062', 'kegiatan' => 'LOMBA TINGKAT KECAMATAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.063', 'kegiatan' => 'LOMBA TINGKAT KOTA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.064', 'kegiatan' => 'LOMBA TINGKAT PROVINSI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.065', 'kegiatan' => 'LOMBA TINGKAT NASIONAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.066', 'kegiatan' => 'OLIMPIADE SAINS NASIONAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.067', 'kegiatan' => 'KEGIATAN TASMI\'', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.068', 'kegiatan' => 'TURNAMEN FUTSAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.069', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER HADROH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.070', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER CATUR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.071', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER ANIMASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.072', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER TAKRAW', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.073', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER ATLETIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.074', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER DESIGN GRAFIS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.075', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER SENI KRIYA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.076', 'kegiatan' => 'PELAKSANAAN KEGIATAN EKSTRAKULIKULER STORY TELLING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.077', 'kegiatan' => 'HIDROPONIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.078', 'kegiatan' => 'KEMAH PRAMUKA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.079', 'kegiatan' => 'GEBYAR DARUSSALAM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.080', 'kegiatan' => 'LOMBA KOMPETENSI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.081', 'kegiatan' => 'KEGIATAN LITERASI DAN NUMERASI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.082', 'kegiatan' => 'KEGIATAN PENANGANAN DAN PENCEGAHAN KEKERASAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.083', 'kegiatan' => 'HARI AMAL BAKTI KEMENAG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.084', 'kegiatan' => 'PROGRAM MAGANG JEPANG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.085', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER ROBOTIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.086', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER PANTOMIM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.087', 'kegiatan' => 'KEGIATAN PMR/ PMI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.088', 'kegiatan' => 'KOMPETISI (OLIMPIADE) SAIN MADRASAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.089', 'kegiatan' => 'KEGIATAN EKSTRAKURIKULER SAINS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.03.090', 'kegiatan' => 'BIMBINGAN TAHFIDZ, TARTIL DAN TAHSIN SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.001', 'kegiatan' => 'PELATIHAN METODE PEMBELAJARAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.002', 'kegiatan' => 'UP GRADING & TEAM BUILDING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.003', 'kegiatan' => 'PELATIHAN KEPSEK & KEPALA DEPARTEMEN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.004', 'kegiatan' => 'PELATIHAN GURU ISLAM TERPADU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.005', 'kegiatan' => 'PELATIHAN GURU BIDANG STUDI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.006', 'kegiatan' => 'STUDI BANDING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.007', 'kegiatan' => 'BIMBINGAN TAHFIDZ, TARTIL DAN TAHSIN GURU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.008', 'kegiatan' => 'KEGIATAN KKG/MGMP ATAU KKKS/MKKS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.009', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI EVALUASI PEMBELAJARAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.010', 'kegiatan' => 'PELATIHAN PEMBUATAN CLOUDING DATA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.011', 'kegiatan' => 'PELATIHAN GURU DAN KEPALA SEKOLAH TERKAIT PERUNDUNGAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.012', 'kegiatan' => 'PROGRAM UMROH GURU & KARYAWAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.013', 'kegiatan' => 'PENYELENGGARAAN KURSUS ICT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.014', 'kegiatan' => 'PENYELENGGARAAN GURU BERPRESTASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.015', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI PENGELOLAAN KEUANGAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.016', 'kegiatan' => 'WORKSHOP PENINGKATAN KOMPETENSI BIDANG ADMINISTRASI SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.017', 'kegiatan' => 'PEMBINAAN TENAGA KETATAUSAHAAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.018', 'kegiatan' => 'PEMBINAAN TENAGA PERPUSTAKAAN/PENINGKATAN KOMPETENSI TENAGA PERPUSTAKAAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.019', 'kegiatan' => 'PELATIHAN KEAMANAN & KESELAMATAN KERJA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.020', 'kegiatan' => 'PELATIHAN EXCEL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.021', 'kegiatan' => 'PROGRAM GURU PENGGERAK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.022', 'kegiatan' => 'PEMBINAAN KEPRIBADIAN GURU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.023', 'kegiatan' => 'PEMBINAAN TENAGA KEAMANAN & TENAGA KEBERSIHAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.024', 'kegiatan' => 'DAUROH TAHFIDZ', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.025', 'kegiatan' => 'KEGIATAN LITERASI GURU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.04.026', 'kegiatan' => 'KEGIATAN PENGAJIAN BULANAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.001', 'kegiatan' => 'PEMBANGUNAN RUANG KELAS BARU (RKB)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.002', 'kegiatan' => 'PEMBANGUNAN SARANA IBADAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.003', 'kegiatan' => 'PENAMBAHAN RUANG IBADAH SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.004', 'kegiatan' => 'PENAMBAHAN RUANG LABORATORIUM KOMPUTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.005', 'kegiatan' => 'PENAMBAHAN RUANG PERPUSTAKAAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.006', 'kegiatan' => 'PENAMBAHAN RUANG KANTOR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.007', 'kegiatan' => 'PEMBUATAN TOILET', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.008', 'kegiatan' => 'BELANJA MODAL ALAT BENGKEL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.009', 'kegiatan' => 'BELANJA MODAL ALAT KANTOR & RUMAH TANGGA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.010', 'kegiatan' => 'BELANJA MODAL ALAT STUDIO DAN KOMUNIKASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.011', 'kegiatan' => 'BELANJA MODAL ALAT LABORATORIUM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.012', 'kegiatan' => 'BELANJA MODAL KOMPUTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.013', 'kegiatan' => 'PERALATAN OLAHRAGA SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.014', 'kegiatan' => 'BELANJA MODAL BUKU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.015', 'kegiatan' => 'BELANJA MODAL BARANG KESENIAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.016', 'kegiatan' => 'BELANJA MODAL TANAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.017', 'kegiatan' => 'BELANJA MODAL BANGUNAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.018', 'kegiatan' => 'PENGADAAN PAPAN PENGUMUMAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.019', 'kegiatan' => 'PENGADAAN MEUBELAIR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.020', 'kegiatan' => 'PENGADAAN PROYEKTOR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.021', 'kegiatan' => 'PENAMBAHAN RUANG KEGIATAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.022', 'kegiatan' => 'PENGADAAN PRINTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.05.023', 'kegiatan' => 'PENGADAAN PAPAN TULIS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.001', 'kegiatan' => 'AKREDITASI SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.002', 'kegiatan' => 'PERJALANAN DINAS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.003', 'kegiatan' => 'PENGELOLAAN INVENTARIS BARANG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.004', 'kegiatan' => 'PENGEMBANGAN SISTEM INFORMASI MANAJEMEN (WEBSITE, E-LEARNING, SOSIAL MEDIA)', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.005', 'kegiatan' => 'PENYUSUNAN LEAFLET, POSTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.006', 'kegiatan' => 'SOSIALISASI KEBIJAKAN-KEBIJAKAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.007', 'kegiatan' => 'PENYUSUNAN RKAS DAN LAPORAN DANA BOS/ BOP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.008', 'kegiatan' => 'PENYUSUNAN RAPBS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.009', 'kegiatan' => 'PENYUSUNAN JADWAL PELAJARAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.010', 'kegiatan' => 'STANDAR ISO', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.011', 'kegiatan' => 'PROGRAM EKSTERNAL AUDIT KEUANGAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.012', 'kegiatan' => 'KEGIATAN PUBLIKASI & MEDIA SOSIAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.013', 'kegiatan' => 'PEMBUATAN KALENDER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.014', 'kegiatan' => 'RAPAT KERJA TAHUNAN PENGURUS YAYASAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.015', 'kegiatan' => 'PELAPORAN & PERENCANAAN KERJA KEPALA SEKOLAH - KEPALA DEPARTEMEN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.016', 'kegiatan' => 'PERINGATAN HUT RI & PENGHARGAAN PENGABDIAN, GURU BERPRESTASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.017', 'kegiatan' => 'PENYULUHAN KESEHATAN BAGI GURU & KARYAWAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.018', 'kegiatan' => 'KEGIATAN POS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.019', 'kegiatan' => 'PELAKSANAAN MOU KERJASAMA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.020', 'kegiatan' => 'PENGELOLAAN TABUNGAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.021', 'kegiatan' => 'PENYUSUNAN SOP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.022', 'kegiatan' => 'DANA ORGAN YAYASAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.023', 'kegiatan' => 'PENGELOLAAN DATABASE PENDIDIKAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.024', 'kegiatan' => 'KEGIATAN HOME VISIT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.025', 'kegiatan' => 'KEGIATAN PARENTING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.06.026', 'kegiatan' => 'HALAL BI HALAL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.001', 'kegiatan' => 'KONSUMSI MAKAN SIANG GURU & KARYAWAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.002', 'kegiatan' => 'KONSUMSI KANTOR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.003', 'kegiatan' => 'KONSUMSI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.004', 'kegiatan' => 'KONSUMSI TAMU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.005', 'kegiatan' => 'KONSUMSI RAPAT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.006', 'kegiatan' => 'BELANJA BAHAN BAKAR MINYAK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.007', 'kegiatan' => 'PEMELIHARAAN GEDUNG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.008', 'kegiatan' => 'PERBAIKAN KERUSAKAN RINGAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.009', 'kegiatan' => 'PEMELIHARAAN TAMAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.010', 'kegiatan' => 'PEMELIHARAAN INVENTARIS & PERALATAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.011', 'kegiatan' => 'PENGADAAN PERLENGKAPAN INDIVIDU SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.012', 'kegiatan' => 'PENGADAAN PERALATAN KEBERSIHAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.013', 'kegiatan' => 'PENGADAAN PERALATAN RUANG UKS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.014', 'kegiatan' => 'PROTOKOL KESEHATAN COVID-19', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.015', 'kegiatan' => 'BELANJA ALAT TULIS KANTOR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.016', 'kegiatan' => 'BELANJA OBAT-OBATAN UKS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.017', 'kegiatan' => 'BELANJA BAHAN KEBERSIHAN HABIS PAKAI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.018', 'kegiatan' => 'BELANJA KERUMAHTANGGAAN LAINNYA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.019', 'kegiatan' => 'PEMBAYARAN TAGIHAN LISTRIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.020', 'kegiatan' => 'PEMBAYARAN TAGIHAN INTERNET', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.021', 'kegiatan' => 'PEMBAYARAN TAGIHAN AIR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.022', 'kegiatan' => 'PEMBAYARAN TAGIHAN TELEPON', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.023', 'kegiatan' => 'PEMBAYARAN JASA KURIR', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.024', 'kegiatan' => 'PEMBAYARAN PULSA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.025', 'kegiatan' => 'PEMBAYARAN PAKET DATA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.026', 'kegiatan' => 'SEWA GOOGLE DRIVE', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.027', 'kegiatan' => 'SEWA HOSTING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.028', 'kegiatan' => 'SEWA WA BLASTER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.029', 'kegiatan' => 'LANGGANAN KORAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.030', 'kegiatan' => 'SEWA AIR FRESHENER', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.031', 'kegiatan' => 'SEDOT WC', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.032', 'kegiatan' => 'PENYEDIAAN AIR BERSIH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.033', 'kegiatan' => 'PENAMBAHAN DAYA LISTRIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.034', 'kegiatan' => 'INSTALASI LISTRIK BARU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.035', 'kegiatan' => 'INSTALASI JARINGAN INTERNET BARU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.036', 'kegiatan' => 'INSTALASI AIR BARU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.037', 'kegiatan' => 'RETRIBUSI PEMBUANGAN SAMPAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.038', 'kegiatan' => 'SEWA GEDUNG/ RUMAH/ TANAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.039', 'kegiatan' => 'BELANJA DANA SOSIAL (TAAWUN)/ KEMASYARAKATAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.040', 'kegiatan' => 'PENGADAAN BUKU SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.041', 'kegiatan' => 'PENGADAAN SERAGAM SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.042', 'kegiatan' => 'PENGADAAN SERAGAM GURU', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.043', 'kegiatan' => 'BESUK SISWA SAKIT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.044', 'kegiatan' => 'KEGIATAN VAKSINASI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.045', 'kegiatan' => 'ADMINISTRASI BANK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.046', 'kegiatan' => 'ASURANSI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.047', 'kegiatan' => 'PAJAK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.048', 'kegiatan' => 'TRANSPORTASI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.049', 'kegiatan' => 'KATERING SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.050', 'kegiatan' => 'IURAN DAPODIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.051', 'kegiatan' => 'IURAN KKG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.052', 'kegiatan' => 'IURAN K3S', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.053', 'kegiatan' => 'IURAN HUT RI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.054', 'kegiatan' => 'IURAN BMG KEMENAG', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.055', 'kegiatan' => 'IURAN IGRA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.056', 'kegiatan' => 'BELANJA AIR MINUM', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.057', 'kegiatan' => 'LAUNDRY', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.058', 'kegiatan' => 'SEWA TEMPAT OLAHRAGA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.059', 'kegiatan' => 'SEWA PERALATAN KEGIATAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.07.060', 'kegiatan' => 'FOGGING', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.001', 'kegiatan' => 'ULANGAN HARIAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.002', 'kegiatan' => 'PENILAIAN/ SUMATIF TENGAH SEMESTER GANJIL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.003', 'kegiatan' => 'PENILAIAN AKHIR SEMESTER GANJIL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.004', 'kegiatan' => 'PENILAIAN/ SUMATIF TENGAH SEMESTER GENAP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.005', 'kegiatan' => 'PENILAIAN AKHIR TAHUN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.006', 'kegiatan' => 'CLASS MEETING PENILAIAN AKHIR SEMESTER GANJIL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.007', 'kegiatan' => 'CLASS MEETING PENILAIAN AKHIR TAHUN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.008', 'kegiatan' => 'TRY OUT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.009', 'kegiatan' => 'UJIAN PRAKTIK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.010', 'kegiatan' => 'AKM/ ANBK', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.011', 'kegiatan' => 'UJIAN SEKOLAH', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.012', 'kegiatan' => 'PELAKSANAAN UJI KOMPETENSI SISWA', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.013', 'kegiatan' => 'PELAKSANAAN PRAKTIK INDUSTRI', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.014', 'kegiatan' => 'PELAKSANAAN BURSA KERJA KHUSUS', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.015', 'kegiatan' => 'LEARNING FACTORY', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.016', 'kegiatan' => 'P5 SEMESTER GANJIL', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.017', 'kegiatan' => 'P5 SEMESTER GENAP', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.018', 'kegiatan' => 'KEGIATAN PEMANTAPAN', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.019', 'kegiatan' => 'KEGIATAN ASSESMEN MINAT BAKAT', 'budget_rapbs' => 0, 'id_unit' => 3],
        // ['kode_kegiatan' => '05.08.020', 'kegiatan' => 'PENINGKATAN MUTU PRAKTIK IBADAH', 'budget_rapbs' => 0, 'id_unit' => 3],

        ];

        foreach ($kegiatan as $data) {
            Kegiatan::create($data);
        }
    }
}
